<?php

namespace Devesharp\Generators;


use Devesharp\Generators\Common\BaseGeneratorAbstract;
use Devesharp\Generators\Common\TemplateGenerator;

class MigrationGenerator extends TemplateGenerator
{
    public string $resourceType = 'migration';

    public function getFileName(): string
    {
        return $this->templateData->now . '_create_' . $this->templateData->tableName . '_table.php';
    }

    public function getTemplateFilename(): string
    {
        return 'devesharp-generators::Migration/migration-table';
    }

    public function getData(): array
    {
        return [];
    }

    public function handle()
    {
        $filename = $this->getPath();

        foreach (glob($filename . '/*', GLOB_MARK) as $file) {
            // Não vai criar outro migrate se já existir um
            if (preg_match('/(.*)_create_' . $this->templateData->tableName . '_table.php/', $file)) {
                return;
            }
        }

        return parent::handle(); // TODO: Change the autogenerated stub
    }
}
