<?php

namespace Devesharp\Console\Commands;

use Illuminate\Console\GeneratorCommand;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Str;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;

class MakeRepository extends GeneratorBase
{
    protected $name = 'ds:repository';

    protected $description = 'Create a new repository';

    protected $type = 'Repository';

    protected string $folder = 'Repositories';

    protected function getStub()
    {
        return  __DIR__ . '/Stubs/repository.stub';
    }

    public function handle()
    {
        try {
            if ($this->option('model') || $this->option('all')) {
                $this->callSilent('ds:model', [
                    'module' => Str::studly($this->argument('module')),
                    'name' => Str::studly($this->argument('name')),
                    '--migration' => $this->option('migration') || $this->option('all')
                ]);
            }
        } catch (\Exception $e) {}

        try {
            if ($this->option('factory') || $this->option('all')) {
                $this->callSilent('ds:factory', [
                    'module' => Str::studly($this->argument('module')),
                    'name' => Str::studly($this->argument('name')),
                ]);
            }
        } catch (\Exception $e) {}


        return parent::handle(); // TODO: Change the autogenerated stub
    }

    protected function getOptions()
    {
        return [
            ['all', 'a', InputOption::VALUE_NONE, ''],
            ['migration', 'm', InputOption::VALUE_NONE, ''],
            ['factory', 'f', InputOption::VALUE_NONE, ''],
            ['model', 'o', InputOption::VALUE_NONE, ''],
        ];
    }
}
